### ISSUE TITLE
Signup/Login with mobile phone number component

### ISSUE THREAD

**Issue by jimmywongz** [oursky/react-native-oursky#2]
**Layout Implementation**
   - [ ] Implement `Get Started` title
   - [ ] Implement the box
       - [ ] with shadow
   - [ ] Country Picker
   - [ ] Mobile Number
      - [ ] Should only allow inputting `Number`, 
      - [ ] When input alphabetical, should not show any text on the input field
   - [ ] For multilingual
   - [ ] For different screen size (Please provide the following device screencap after the implementation)
      - [ ] Iphone XS Max 
      - [ ] Iphone X
      - [ ] Iphone SE
      - [ ] Nexue 5
      - [ ] Samsung note 9

**Entering page**
- [ ] Should show the keyboard in `phone-pad` immediately  

**Button Behaviour**
- After pressing `Country picker`
   - [ ] Should open the country selection page
- After pressing `Next` button
   - [ ] Should check the validation in local 
      - [ ] Country code selection
          - [ ] Required
      - [ ] Mobile Number Input field
          - [ ] Numeric only
   - [ ] If the validation failed, show the validation error message 
   - [ ] If the validation is passed, show the spinner on the button and disable the button
   - [ ] Trigger to retrieve SMS request
- [ ] No need to handle `Skip for now` button

 
<img width="376" alt="screenshot 2018-11-26 at 3 25 55 pm" src="https://user-images.githubusercontent.com/38206404/48998878-dae72980-f18f-11e8-94d6-98b648128991.png">
<img width="375" alt="screenshot 2018-11-26 at 3 26 23 pm" src="https://user-images.githubusercontent.com/38206404/48998881-dc185680-f18f-11e8-9ca0-6063cb0bd7f3.png">

**Comment by shana0440** [comment]
The goal of this component is it should be easy to reuse by any project, so it must be responsive for any device size.

**Comment by jimmywongz** [comment]
@shana0440 yes, thanks

**Comment by shana0440** [comment]
I prepare to create a component have this props. and default style is like the above image.

```ts
export interface Mobile {
  countryCode: string | null;
  no: string | null;
}

interface Props {
  style?: StyleProps<ViewStyle>;
  containerStyle?: StyleProps<ViewStyle>;

  header?: string;
  headerStyle?: StyleProps<TextStyle>;
  descript?: string;
  descriptStyle?: StyleProps<TextStyle>;
  title?: string;
  titleStyle?: StyleProps<TextStyle>;
  
  countryPickerStyle?: StyleProps<ViewStyle>;
  mobileNumberFieldStyle?: StyleProps<ViewStyle>;
  
  buttonText?: string;
  buttomStyle?: StyleProps<ViewStyle>;

  skipText?: string;
  skipStyle?: StyleProps<ViewStyle>;

  onPressButton?: (mobile: Mobile) => void;
  onPressSkip?: () => void;
}
```

**Comment by cychiuae** [comment]
I believe we should first create a text input component .
![screenshot 2018-11-27 at 6 45 10 pm](https://user-images.githubusercontent.com/10144357/49076710-97b2b680-f274-11e8-9c85-adb5c2a2077e.png)
From what I know, this textinput will also be reused many times. It consists of two part, one is the textinput itself and the other part is option text below the under. It also should be able to accept error and shows error message instead of option text in error is set.

@shana0440 Can you plan for that first?

After that, I believe you should plan for the country picker list. 

Btw,  type of mobile should be 

```ts
type CountryCallingCode = "852" | "44" | "886" .....;

interface Mobile {
  countryCallingCode: CountryCallingCode;
  nationalNumber: string;  
}

// or 

interface Mobile {
  countryCallingCode: string;
  nationalNumber: string;  
}

// if the first one is too complicated to do
```

No matter which one, its properties should not `null`

Also, I've got some question on your component props definition.
1. What are the differences between `styles` and `containerStyles`?
2. `header` gives a feel that it should be a element or component instead of string.
3.  descript? Do you mean `description`?
4. Which part do your refer to when you use `title`?
5. As I said above, mobile number text input should use a reused version of textinput to implement, I think you need to re-plan about props related to it.
6. You should make a more accurate name instead of `buttonText`
7. `skipStyle` is not good enough cover our use cases. How can we set the skip button text styles or skip button styles?

**Comment by shana0440** [comment]
@cychiuae ok, I will plan TextInput first.
And this is the answer to your question.
1. style include `Get Started`, containerStyle is the style of the box.
2. I will think a better name.
3. yes, thanks :D
4. `Your mobile no.`
5. yes, after I finish TextInput I will re-plan this component.
6. I will think a better name.
7. yes, I should have `skipTextStyle` & `skipButtonStyle`.

**Comment by shana0440** [comment]
I think the Props of TextInput will be
```
export interface Props extends TextInputProps {
  error?: string | null;
  errorStyle?: TextStyle;
  optionText?: string;
  optionTextStyle?: TextStyle;
}
```
if error is not undefined, I will create a nonvisible text below the textinput, avoid layout unstable.

**Comment by shana0440** [comment]
I plan to create a Select Component first, the props of the Select will be
```ts
interface Props {
  style?: ViewStyle;
  textStyle?: TextStyle;
  placeholder?: string;
  placeholderTextColor?: string;
  selectedValue?: string;
  options?: string[];

  onValueChange?: (value: string) => void;
}
```
I think this component will make create CountryPicker more easier.

**Comment by jimmywongz** [comment]
@shana0440 please help to start creating the component and submit the PR, Thanks :)

**Comment by jimmywongz** [comment]
Hi @shana0440 ,

For the country code picker, please use the following library:
https://www.dropbox.com/s/m4oygotnjy1egzg/component-countrylistpicker.zip?dl=0

![page-1-countrylist-simple](https://user-images.githubusercontent.com/38206404/49213329-04f25300-f3ff-11e8-802c-621c9a16e1c4.png)

## TODO

- [ ] Should auto select the current country code accoriding to the simcard location
- [ ] In the searching bar, it should be allowed to search by different language, for example
   - [ ] Search `Hong Kong` -> If the app is in Chinese, `香港` will be shown in the list
- [ ] In the searching bar, it should also be allowed to search by country code, for example
   - [ ] Search `85` -> the result should show Hong Kong as one of the results

**Comment by shana0440** [comment]
@rickmak @louischan-oursky 
This package should include language data or the language data is user should prepare?

**Comment by louischan-oursky** [comment]
I agree we should not trigger HTTP request. However, we can declare a `peerDependency` with `^major_version.minor_version.patch_version` on https://github.com/catamphetamine/libphonenumber-js to provide phone number validation. Since react-native-oursky currently is not setup to provide native modules, we cannot implement features that require native modules. We definitely want to support native modules. But let's focus on pure JS component first.

**Comment by shana0440** [comment]
@jimmywongz this is the screencap. I can't found Samsung note 9 emulator so the screencap doesn't incloude that.
![screen shot 2018-12-03 at 11 55 31 am](https://user-images.githubusercontent.com/6259797/49352516-403c9c80-f6f3-11e8-9ad0-cfc70ac26f49.png)
![screen shot 2018-12-03 at 11 55 57 am](https://user-images.githubusercontent.com/6259797/49352519-43378d00-f6f3-11e8-9c6d-254da0b78175.png)
![screen shot 2018-12-03 at 11 58 01 am](https://user-images.githubusercontent.com/6259797/49352521-45015080-f6f3-11e8-90f0-a929ca4bf1fc.png)

**Comment by jimmywongz** [comment]
- [ ] Please help to declare a peerDependency with ^major_version.minor_version.patch_version on https://github.com/catamphetamine/libphonenumber-js
- [ ] Please help to adjust the layout according to the below guideline
<img width="1022" alt="screenshot 2018-12-03 at 12 32 08 pm" src="https://user-images.githubusercontent.com/38206404/49353239-aaefd700-f6f7-11e8-8a75-b915082e022b.png">

**Comment by shana0440** [comment]
@jimmywongz new screenshot
![screen shot 2018-12-03 at 2 54 41 pm](https://user-images.githubusercontent.com/6259797/49357815-79810680-f70b-11e8-90c9-994921b2246a.png)

**Comment by jimmywongz** [comment]
@shana0440 looks good to me.

**Comment by rickmak** [comment]
@frank-oursky please check.

**Comment by jimmywongz** [comment]
@shana0440 
- In the country selection page
   1. Enter "852" in the search bar
   2. Hong Kong can be displayed
   3. Remove 852
   4. One result can be displayed

**TODO**
- [ ] Should display all the result if there is no any character in the searching bar
